version: "3.7"
services:

  nginx:
    image: nginx:1.19.5
    networks:
      - gis_2ban_network
    volumes:
      - gis_media:/data/media/
      - gis_static:/data/static/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80

  django:
    image: gis_test_image:3
    networks:
      - gis_2ban_network
    volumes:
      - gis_media:/home/gis_2ban/media/
      - gis_static:/home/gis_2ban/staticfiles/

networks:
  gis_2bna_network

volumes:
  gis_2ban_media:
  gis_2ban_static: