version: "3.7"
services:

  nginx:
    image: nginx:1.19.5
    networks:
      - gis_2ban_network
    volumes:
      - gis_media:/data/media/
      - gis_static:/data/static/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: gis_image_test:4
    networks:
      - gis_2ban_network
    volumes:
      - gis_media:/home/gis_2ban/media/
      - gis_static:/home/gis_2ban/staticfiles/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_2ban_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: qwer1
      MARIADB_ROOT_PASSWORD: qwer1


networks:
  gis_2ban_network:

volumes:
  gis_media:
  gis_static:
  gis_mariadb: